In [645]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error

In [646]:
df = pd.read_csv("Most_Recent_Messydata.csv")

In [647]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Email', 'Phone_Number', 'City',
       'Department', 'Salary', 'Joining_Date', 'Experience_Years',
       'Performance_Score', 'Manager_ID', 'Work_Location', 'Bonus_Percentage',
       'Remote_Onsite'],
      dtype='object')

In [648]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6081 entries, 0 to 6080
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 6081 non-null   int64
 1   Name               5956 non-null   object
 2   Age                6020 non-null   object
 3   Gender             5297 non-null   object
 4   Email              6015 non-null   object
 5   Phone_Number       6004 non-null   object
 6   City               5485 non-null   object
 7   Department         5546 non-null   object
 8   Salary             6026 non-null   object
 9   Joining_Date       5970 non-null   object
 10  Experience_Years   6017 non-null   float64
 11  Performance_Score  5413 non-null   object
 12  Manager_ID         6012 non-null   float64
 13  Work_Location      5346 non-null   object
 14  Bonus_Percentage   5950 non-null   float64
 15  Remote_Onsite      5061 non-null   object
dtypes: float64(3), int64(1), object(12)
memory usage: 760.3+ KB

In [649]:
df.describe()

                 ID  Experience_Years    Manager_ID  Bonus_Percentage
count   6081.000000       6017.000000   6012.000000       5950.000000
mean   14988.089459         10.671431  11738.533100         16.544874
std     2861.793780          7.647328  11856.387981         16.257714
min    10000.000000         -3.000000  10000.000000        -10.000000
25%    12542.000000          5.000000  10025.000000          7.000000
50%    14975.000000         10.000000  10052.000000         15.000000
75%    17470.000000         16.000000  10078.000000         23.000000
max    19999.000000         50.000000  99999.000000        150.000000

In [650]:
missing=df.isnull().sum().sort_values(ascending=False)
missing_percent=(missing/len(df))*100
pd.DataFrame({
    "Missing_count": missing,
    "Missing_percent": missing_percent
})

                   Missing_count  Missing_percent
Remote_Onsite               1020        16.773557
Gender                       784        12.892616
Work_Location                735        12.086828
Performance_Score            668        10.985035
City                         596         9.801020
Department                   535         8.797895
Bonus_Percentage             131         2.154251
Name                         125         2.055583
Joining_Date                 111         1.825358
Phone_Number                  77         1.266239
Manager_ID                    69         1.134682
Email                         66         1.085348
Experience_Years              64         1.052458
Age                           61         1.003124
Salary                        55         0.904457
ID                             0         0.000000

In [651]:
df.duplicated().sum()

np.int64(6)

In [652]:
df.drop_duplicates(inplace = True)

In [653]:
df

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39,NaN,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31,NaN,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41,M,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39,NaN,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19,Male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6076,18150,Kevin Campbell,24,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48,NaN,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18,NaN,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote
6080,10656,Leslie Hansen,21,NaN,j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [654]:
df.duplicated().sum()

np.int64(0)

In [655]:
df['Name'].isnull().sum()

np.int64(124)

In [656]:
# df['column_name'] = df['column_name'].str.strip().str.replace(r'\s+', '' ,regex = True)

In [657]:
extra_space_names = df[df['Name'].str.startswith(' ') | df['Name'].str.endswith(' ')]

In [658]:
print("Total names with extra spaces:" ,len(extra_space_names))

Total names with extra spaces: 126

In [659]:
import re
# Function to check if a name has special characters
def has_special_char(name):
    if pd.isnull(name):
        return False
    return bool(re.search(r'[^a-zA-Z\s]', name))

special_char_names = df[df['Name'].apply(has_special_char)]
special_char_names.head(20)

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
87,16021,Dr. Phillip Austin,20,female,richardjones@gmail.com,368.326.6659x394,Mumbai,Sales,93125,"Oct 27, 2024",15.0,3,10061.0,Hyderabad,30.0,Onsite
132,17459,Scott Bates Jr.,62,Male,fordgerald@yahoo.com,+1-103-135-1436,mumbai,HR,44204,2024-11-26,12.0,1,10016.0,Mmbai,10.0,Remote
177,16971,Mr. Fernando Pena DVM,26,male,caineric@rodriguez.com,001-707-292-9713x59237,Bangalor,HR,62535,2025-07-15,4.0,NaN,88888.0,Hyderabad,19.0,remote
254,12704,Mr. Philip Webb,61,female,hermankyle@santiago-green.org,+1-568-666-0363x473,Mmbai,Operations,129427,2025-12-28,7.0,Good,10033.0,Mumbai,-10.0,Hybrid
275,13053,Perry Villegas Jr.,60,Female,jeremy15@copeland.biz,001-507-697-8881x08694,Hyderabad,Marketing,116321,2023-12-19,6.0,5,10006.0,Mmbai,14.0,Hybrid
290,19378,Mr. Patrick Bennett Jr.,54,NaN,tflynn@underwood.info,(768)352-6971x361,Mumbai,IT,95241,2017-04-26,30.0,1,10047.0,Mmbai,29.0,Remote
292,16585,Mrs. Cindy Maldonado,29,female,camposnicole@yahoo.com,837-199-2031,Hyderabad,Sales,129835,2016-04-03,16.0,Excellent,10040.0,Mumbai,27.0,NaN
320,16871,Dr. Maurice Beasley DDS,-20,NaN,robert70@hughes-ramirez.com,1566126900,Mmbai,hr,98953,2024-08-02,0.0,2,10078.0,Mumbai,28.0,Hybrid
321,17013,Mr. Dwayne Perez,44,Male,sydney59@gmail.com,771.637.4753,NaN,Operations,30340,2024-10-23,20.0,1,10026.0,Mmbai,25.0,Hybrid
411,12235,Dr. James Fisher,18,NaN,brandon73@gutierrez.org,755.948.0608x8724,Delhi,sales,64667.1,2021-07-14,20.0,Poor,10047.0,Mmbai,4.0,onsite
421,17532,Dr. Monica Franklin,33,female,elizabethhancock@lee.com,290-436-3649x7982,Hyderabad,Finance,145212,2020-07-06,12.0,Excellent,10070.0,NaN,3.0,Hybrid
429,11524,Mr. Steven Miller,35,Male,vsmith@hotmail.com,(974)449-9861x6474,Mmbai,Marketing,44592.31,2025-12-13,2.0,NaN,10029.0,NaN,22.0,Remote
465,15460,Mrs. Diana Robinson,48.8,male,annettesmith@yahoo.com,(091)045-6766x531,mumbai,Financ,102509,2024-08-16,12.0,Poor,10018.0,Delhi,6.0,Remote
527,16745,Mr. Evan Byrd,61,Male,philipreyes@gallagher.org,880-377-1079,Mumbai,NaN,120636,2024-01-20,16.0,2,10063.0,Chennai,3.0,Hybrid
550,16769,Mrs. Katrina Pearson,24,M,zharrington@roberts.org,571-272-1937x21713,Chennai,Sales,101580,2023-01-10,25.0,2,10049.0,Delhi,18.0,Onsite
579,12160,Dr. Laurie Nguyen,thirty-two,Female,jarnold@wright-king.biz,(924)322-3135,Bangalor,sales,76833,2016-10-16,12.0,Good,10001.0,Hyderabad,18.0,Remote
645,13145,Walter Flores Jr.,65,female,brian59@rojas.com,(625)865-7933,mumbai,IT,79747.41,2025-01-15,17.0,4,10034.0,Mmbai,1.0,onsite
732,11005,Mrs. Yvonne Chavez,43,M,hcarpenter@osborne-miranda.net,601-053-3229,Mumbai,NaN,61491,2017-08-12,18.0,NaN,10067.0,NaN,128.0,remote
781,15776,Mr. Allen Murray,34,female,udennis@gmail.com,001-321-328-6144x8433,Mmbai,Operations,131883,2017-08-19,13.0,4,88888.0,Chennai,30.0,onsite
809,15900,Dr. Michael Gonzalez,64,M,timothy95@wade-barrera.biz,620-093-8778x019,Mumbai,HR,40239,2020-05-01,17.0,4,10069.0,Delhi,NaN,Hybrid

In [660]:
print("Total names with special characters:" ,len(special_char_names))

Total names with special characters: 138

In [661]:
df['Name'] = df['Name'].fillna('Unknown')

In [662]:
df['Name']

0            Morgan Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [663]:
df['Name'] = df['Name'].astype(str).str.strip()

In [664]:
df['Name']

0            Morgan Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [665]:
# Keep only letters and spaces
df['Name'] = df['Name'].apply(lambda x: re.sub(r'[^a-zA-Z\s]','',x))

In [666]:
df['Name'] = df['Name'].str.title()

In [667]:
df['Name'].head(10)

0        Morgan Reyes
1      Brendan Thomas
2     Jeanette Hooper
3       Jesse Stewart
4     William Maxwell
5      Rachel Shelton
6    Antonio Anderson
7      Colin Robinson
8       Sarah Stevens
9      Nichole Garcia
Name: Name, dtype: object

In [668]:
df['Age'].unique()

array(['39', '31', '41', '19', '56', '62', '63', '20', '51', '38', '33',
       '53', '44', '48', '26', '43', '47', '28', '40', '35', '55', '42',
       'forty-five', '54', '64', '29.2', '57', '32', '27', '37', '25',
       '21', '30', '29', '18', 'twenty', '59', '34', '61', '22', '49',
       '58', '24', '65', '46', '200', '60', '36', '50', '27.4', '45', nan,
       '150', '52', '39.5', '23', '33.5', '-20', '34.7', '48.8', '101',
       '-5', 'thirty-two', '-1', '56.3', '38.1', '35.1', '56.6', '60.4',
       '25.4', '22.4', '59.2', '38.3', '34.3', '21.4', '59.0', '52.7',
       '40.1', '64.8', '33.1', '40.2', '54.5', '47.8', '27.8', '22.9',
       '34.2', '21.3', '38.0', '59.9', '18.6', '25.6', '23.0', '41.9',
       '44.1', '64.3', '47.2', '29.1', '24.7', '37.1', '34.1', '25.5',
       '55.3', '33.0', '52.9', '21.8', '56.1', '58.2', '53.0', '56.4'],
      dtype=object)

In [669]:
missing_count = df['Age'].isna().sum()
print("Missing values in Age:" , missing_count)

Missing values in Age: 61

In [670]:
df['Age'] = df['Age'].astype(str)

In [671]:
def contains_letters(age_value):
    if age_value.lower() == 'nan': #skip nan
        return False
    return any(c.isalpha() for c in age_value) # True if any letter exist

In [672]:
Age_has_letters = df['Age'].apply(contains_letters)

In [673]:
Age_has_letters

0       False
1       False
2       False
3       False
4       False
        ...
6076    False
6077    False
6078    False
6079    False
6080    False
Name: Age, Length: 6075, dtype: bool

In [674]:
non_numeric_ages = df[Age_has_letters]

In [675]:
non_numeric_ages

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
30,10542,Brooke Fritz Md,forty-five,Unknown,hyoung@gmail.com,658-970-2119,Bangalor,Operations,126086,2017-03-31,3.0,4,10079.0,Mmbai,-10.0,NaN
53,10589,Gregory Tanner,twenty,male,ffreeman@hotmail.com,4666519027,Mmbai,Marketing,126761,2025-01-25,7.0,Excellent,10097.0,Bangalore,11.0,Hybrid
256,12974,Catherine Skinner,forty-five,M,escott@yahoo.com,235.266.1142x397,Hyderabad,IT,139977,03/09/2024,NaN,5,10065.0,Bangalore,18.0,Hybrid
294,13724,Leslie Arias,forty-five,F,spencergreg@cruz.com,284.905.5854,Bangalore,Sales,111194,2019-04-13,7.0,Excellent,10084.0,NaN,1.0,remote
356,10799,Katherine Porter,twenty,NaN,orowland@yahoo.com,2718765215,Hyderabad,Operations,55185,2023-06-13,5.0,2,10094.0,Delhi,27.0,Hybrid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5756,10739,Regina Park,thirty-two,female,ijackson@robertson.org,+1-349-858-7776,Hyderabad,NaN,73949,2020-02-24,11.0,Good,10038.0,Mumbai,28.0,onsite
5926,12380,Mike Hawkins,twenty,female,jamesarnold@hotmail.com,5526582771,Delhi,hr,81827,2018-05-27,19.0,Excellent,10028.0,Delhi,11.0,Onsite
6020,19974,Lori Pennington,forty-five,Female,scottsherman@hotmail.com,(690)997-7684,Hyderabad,IT,127758,2016-07-04,4.0,4,10090.0,Chennai,2.0,onsite
6026,14886,Rachel Shaw,forty-five,male,lambertandre@vance-mcpherson.biz,(645)117-5591x893,mumbai,sales,NaN,2020-10-27,4.0,1,10014.0,Bangalor,16.0,Remote
6043,16892,Alan Howell,thirty-two,male,ssimmons@thomas.com,(219)476-4625x71737,delhi,Finance,54725,2019-09-25,7.0,Poor,10056.0,NaN,6.0,Hybrid

In [676]:
non_numeric_ages['Age'].value_counts()

Age
forty-five    23
thirty-two    20
twenty        18
Name: count, dtype: int64

In [677]:
non_numeric_ages['Age'].unique()

array(['forty-five', 'twenty', 'thirty-two'], dtype=object)

In [678]:
df['Age'] = df['Age'].replace(['forty-five', 'twenty', 'thirty-two'] , ['45' , '20' , '32'])

In [679]:
df['Age'] = df['Age'].replace('nan' , np.nan)

In [680]:
df['Age']

0       39
1       31
2       41
3       39
4       19
        ..
6076    24
6077    37
6078    48
6079    18
6080    21
Name: Age, Length: 6075, dtype: object

In [681]:
df['Age'].unique()

array(['39', '31', '41', '19', '56', '62', '63', '20', '51', '38', '33',
       '53', '44', '48', '26', '43', '47', '28', '40', '35', '55', '42',
       '45', '54', '64', '29.2', '57', '32', '27', '37', '25', '21', '30',
       '29', '18', '59', '34', '61', '22', '49', '58', '24', '65', '46',
       '200', '60', '36', '50', '27.4', nan, '150', '52', '39.5', '23',
       '33.5', '-20', '34.7', '48.8', '101', '-5', '-1', '56.3', '38.1',
       '35.1', '56.6', '60.4', '25.4', '22.4', '59.2', '38.3', '34.3',
       '21.4', '59.0', '52.7', '40.1', '64.8', '33.1', '40.2', '54.5',
       '47.8', '27.8', '22.9', '34.2', '21.3', '38.0', '59.9', '18.6',
       '25.6', '23.0', '41.9', '44.1', '64.3', '47.2', '29.1', '24.7',
       '37.1', '34.1', '25.5', '55.3', '33.0', '52.9', '21.8', '56.1',
       '58.2', '53.0', '56.4'], dtype=object)

In [682]:
df['Age'] = pd.to_numeric(df['Age'] , errors = 'coerce')

In [683]:
negative_age = df[df['Age']<0]

In [684]:
negative_age['Age'].value_counts()

Age
-1.0     21
-20.0    16
-5.0     16
Name: count, dtype: int64

In [685]:
#replace the value when condition is floce
df['Age'] = df['Age'].where(df['Age']>=0 , np.nan)

In [686]:
df[df['Age']>=0]

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39.0,NaN,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31.0,NaN,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41.0,M,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39.0,NaN,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19.0,Male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48.0,NaN,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18.0,NaN,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote
6080,10656,Leslie Hansen,21.0,NaN,j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [687]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [688]:
df['Age'] = df['Age'].astype(int)

In [689]:
df['Age'].unique()

array([ 39,  31,  41,  19,  56,  62,  63,  20,  51,  38,  33,  53,  44,
        48,  26,  43,  47,  28,  40,  35,  55,  42,  45,  54,  64,  29,
        57,  32,  27,  37,  25,  21,  30,  18,  59,  34,  61,  22,  49,
        58,  24,  65,  46, 200,  60,  36,  50, 150,  52,  23, 101])

In [690]:
df[df['Age'] == 'NaN']

Empty DataFrame
Columns: [ID, Name, Age, Gender, Email, Phone_Number, City, Department, Salary, Joining_Date, Experience_Years, Performance_Score, Manager_ID, Work_Location, Bonus_Percentage, Remote_Onsite]
Index: []

In [691]:
lower_limit = 18
upper_limit = 65
df.loc[(df['Age'] < lower_limit) | (df['Age'] > upper_limit), 'Age'] = pd.NA

In [692]:
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

# Gender Column

In [693]:
df['Gender'].unique()

array([nan, 'M', 'Male', 'F', 'Unknown', 'Female', 'female', 'male'],
      dtype=object)

In [694]:
df['Gender'] = df['Gender'].str.lower()

In [695]:
df['Gender'].value_counts()

Gender
male       1546
female     1484
m           770
f           754
unknown     737
Name: count, dtype: int64

In [696]:
df['Gender'] = df['Gender'].replace({
    'm':'male',
    'f':'female'
})

In [697]:
df['Gender'].unique()

array([nan, 'male', 'female', 'unknown'], dtype=object)

In [698]:
df['Gender'] = df['Gender'].replace('nan' , np.nan)

In [699]:
df['Gender'].isna().sum()

np.int64(784)

In [700]:
df['Gender'].value_counts()

Gender
male       2316
female     2238
unknown     737
Name: count, dtype: int64

In [701]:
df['Gender'] = df['Gender'].fillna('unknown')

In [702]:
df['Gender'].value_counts()

Gender
male       2316
female     2238
unknown    1521
Name: count, dtype: int64

#  Email

In [703]:
df['Email'].isna().sum()

np.int64(66)

In [704]:
df['Email'].unique()

array(['santanaheidi@simpson.com', 'anthony69@hotmail.com',
       'gutierrezzachary@gmail.com', ..., 'wrose@ortiz-wong.com',
       'cgreen@peters-reyes.info', 'j'], shape=(5937,), dtype=object)

In [705]:
df['Email'] = df['Email'].str.strip()

In [706]:
df['Email'] = df['Email'].str.lower()

In [707]:
df[df['Email'].str.contains('@' , na = False)]

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39.0,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31.0,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41.0,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39.0,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19.0,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,13841,Jennifer Myers,45.0,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48.0,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18.0,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote

In [708]:
df[df['Email'].str.count('@') == 1]

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39.0,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31.0,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41.0,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39.0,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19.0,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,13841,Jennifer Myers,45.0,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48.0,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18.0,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote

In [709]:
df['Email_Domain'] = df['Email'].str.split('@').str[-1]

In [710]:
df

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite,Email_Domain
0,16271,Morgan Reyes,39.0,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite,simpson.com
1,12235,Brendan Thomas,31.0,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite,hotmail.com
2,10743,Jeanette Hooper,41.0,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote,gmail.com
3,19229,Jesse Stewart,39.0,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote,hotmail.com
4,12385,William Maxwell,19.0,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite,abc.org
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite,gmail.com
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid,yahoo.com
6078,18233,Richard Rodriguez,48.0,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote,ortiz-wong.com
6079,14157,Lucas Ramsey,18.0,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote,peters-reyes.info
6080,10656,Leslie Hansen,21.0,unknown,j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,j

In [711]:
df['Email_Domain'].unique()

array(['simpson.com', 'hotmail.com', 'gmail.com', ..., 'ortiz-wong.com',
       'peters-reyes.info', 'j'], shape=(2163,), dtype=object)

In [712]:
df['Email_Domain'].value_counts().head(20)

Email_Domain
gmail.com           1005
yahoo.com            991
hotmail.com          954
smith.com             32
johnson.com           29
company.com           25
williams.com          21
brown.com             17
test.net              15
outlook.com           14
miller.com            14
davis.com             12
thompson.com          12
                      12
rodriguez.com         11
user#domain.com       11
perez.com             11
garcia.com            10
lopez.com              9
user.domain..com       9
Name: count, dtype: int64

In [713]:
df.drop(6080 , inplace = True)

In [714]:
df

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite,Email_Domain
0,16271,Morgan Reyes,39.0,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite,simpson.com
1,12235,Brendan Thomas,31.0,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite,hotmail.com
2,10743,Jeanette Hooper,41.0,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote,gmail.com
3,19229,Jesse Stewart,39.0,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote,hotmail.com
4,12385,William Maxwell,19.0,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite,abc.org
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,13841,Jennifer Myers,45.0,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid,schmidt.com
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite,gmail.com
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid,yahoo.com
6078,18233,Richard Rodriguez,48.0,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote,ortiz-wong.com
6079,14157,Lucas Ramsey,18.0,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote,peters-reyes.info

In [715]:
df['Email_Domain'] = df['Email_Domain'].str.replace('#' , '')

In [716]:
df['Email_Domain'].value_counts().head(30)

Email_Domain
gmail.com           1005
yahoo.com            991
hotmail.com          954
smith.com             32
johnson.com           29
company.com           25
williams.com          21
brown.com             17
test.net              15
miller.com            14
outlook.com           14
davis.com             12
thompson.com          12
                      12
rodriguez.com         11
userdomain.com        11
perez.com             11
garcia.com            10
thomas.com             9
user.domain..com       9
jones.com              9
white.com              9
lopez.com              9
lee.com                8
martinez.com           8
abc.org                7
gonzalez.com           7
green.com              7
hernandez.com          7
sanchez.com            7
Name: count, dtype: int64

In [717]:
df['Email_Domain'] = df['Email_Domain'].str.replace('-' , '')

In [718]:
df['Email_Domain'].value_counts()

Email_Domain
gmail.com              1005
yahoo.com               991
hotmail.com             954
smith.com                32
johnson.com              29
                       ...
smithwilliams.com         1
williamsrobbins.net       1
glover.org                1
keller.biz                1
lewismoore.com            1
Name: count, Length: 2161, dtype: int64

In [719]:
df['Email_Domain'].value_counts().head(20)

Email_Domain
gmail.com           1005
yahoo.com            991
hotmail.com          954
smith.com             32
johnson.com           29
company.com           25
williams.com          21
brown.com             17
test.net              15
miller.com            14
outlook.com           14
davis.com             12
thompson.com          12
                      12
rodriguez.com         11
userdomain.com        11
perez.com             11
garcia.com            10
thomas.com             9
user.domain..com       9
Name: count, dtype: int64

In [720]:
df['Email_Domain'].unique()

array(['simpson.com', 'hotmail.com', 'gmail.com', ...,
       'petersmitchell.net', 'ortizwong.com', 'petersreyes.info'],
      shape=(2162,), dtype=object)

In [721]:
df['Email_Domain'] = df['Email_Domain'].str.lower().str.strip().str.replace(r'\.+', '.', regex=True)

In [722]:
df['Email_Domain']

0            simpson.com
1            hotmail.com
2              gmail.com
3            hotmail.com
4                abc.org
              ...
6075         schmidt.com
6076           gmail.com
6077           yahoo.com
6078       ortizwong.com
6079    petersreyes.info
Name: Email_Domain, Length: 6074, dtype: object

In [723]:
df['Email_Domain'].value_counts().head(20)

Email_Domain
gmail.com          1005
yahoo.com           991
hotmail.com         954
smith.com            32
johnson.com          29
company.com          25
williams.com         21
brown.com            17
test.net             15
miller.com           14
outlook.com          14
davis.com            12
thompson.com         12
                     12
rodriguez.com        11
userdomain.com       11
perez.com            11
garcia.com           10
thomas.com            9
user.domain.com       9
Name: count, dtype: int64

In [724]:
# df['Email_Domain'] = (
#     df['Email_Domain']
#     .str.lower()
#     .str.strip()
#     .str.replace(r'\.+', '', regex=True) # remove all extra dots
#     .str.replace(r'(com|net|org|info|edu)$', r'.\1', regex=True)  # add single dot before extension
# )

In [725]:
df['Email_Domain']

0            simpson.com
1            hotmail.com
2              gmail.com
3            hotmail.com
4                abc.org
              ...
6075         schmidt.com
6076           gmail.com
6077           yahoo.com
6078       ortizwong.com
6079    petersreyes.info
Name: Email_Domain, Length: 6074, dtype: object

In [726]:
# df['Email_Domain'].value_counts().head(20)

In [727]:
# df['email_last'] = df['Email_Domain'].str.rsplit('.', n=1).str[-1]
# df['email_domain_first'] = df['Email_Domain'].str.rsplit('.', n=1).str[0]
# df['email_domain_first'] = df['email_domain_first'].str.replace('.', '', regex=False)

In [728]:
# df['merged_email_domain'] = df['email_domain_first'] + '.' + df['email_last']

In [729]:
# df

In [730]:
# df.drop(columns = ['Email_Domain' , 'email_last' , 'email_domain_first' ] , axis = 1 , inplace = True)

In [731]:
df

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite,Email_Domain
0,16271,Morgan Reyes,39.0,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite,simpson.com
1,12235,Brendan Thomas,31.0,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite,hotmail.com
2,10743,Jeanette Hooper,41.0,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote,gmail.com
3,19229,Jesse Stewart,39.0,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote,hotmail.com
4,12385,William Maxwell,19.0,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite,abc.org
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,13841,Jennifer Myers,45.0,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid,schmidt.com
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite,gmail.com
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid,yahoo.com
6078,18233,Richard Rodriguez,48.0,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote,ortizwong.com
6079,14157,Lucas Ramsey,18.0,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote,petersreyes.info

In [732]:
# df['merged_email_domain'].value_counts().head(20)

In [733]:
df['Email_Domain'] = df['Email_Domain'].replace('user.domain.com', 'userdomain.com')

In [734]:
df['Email_Domain']

0            simpson.com
1            hotmail.com
2              gmail.com
3            hotmail.com
4                abc.org
              ...
6075         schmidt.com
6076           gmail.com
6077           yahoo.com
6078       ortizwong.com
6079    petersreyes.info
Name: Email_Domain, Length: 6074, dtype: object

In [735]:
df['Email_Domain'].value_counts().head(20)

Email_Domain
gmail.com         1005
yahoo.com          991
hotmail.com        954
smith.com           32
johnson.com         29
company.com         25
williams.com        21
userdomain.com      20
brown.com           17
test.net            15
outlook.com         14
miller.com          14
                    12
davis.com           12
thompson.com        12
perez.com           11
rodriguez.com       11
garcia.com          10
jones.com            9
white.com            9
Name: count, dtype: int64

In [736]:
df['Email_Domain'] = df['Email_Domain'].fillna('unknown@gmail.com')

In [737]:
df['Email_Domain'] = df['Email_Domain'].replace({
    'gamil.com':'gmail.com',
    'yahooo.com':'yahoo.com',
})

In [738]:
df['Email_Domain'] = df['Email_Domain'].replace('nan' , np.nan)

In [739]:
#  Keep domains appearing >= 50 times, other became 'Other'
counts = df['Email_Domain'].value_counts()

In [740]:
counts

Email_Domain
gmail.com              1005
yahoo.com               991
hotmail.com             954
unknown@gmail.com        66
smith.com                32
                       ...
morton.com                1
smithwilliams.com         1
williamsrobbins.net       1
glover.org                1
lewismoore.com            1
Name: count, Length: 2161, dtype: int64

In [741]:
rare_domains = counts[counts < 50].index
df['Domain'] = df['Email_Domain'].replace(rare_domains, 'Other')

In [742]:
df['Domain']

0             Other
1       hotmail.com
2         gmail.com
3       hotmail.com
4             Other
           ...
6075          Other
6076      gmail.com
6077      yahoo.com
6078          Other
6079          Other
Name: Domain, Length: 6074, dtype: object

In [743]:
free_domains = ['gmail.com', 'yahoo.com' , 'hotmail.com']
df['Email_Type'] = df['Email_Domain'].apply(lambda x: 'personal' if x in free_domains else 'corporate')

In [744]:
corporate_users = df[df['Email_Type'] == 'corporate']

In [745]:
corporate_users

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite,Email_Domain,Domain,Email_Type
0,16271,Morgan Reyes,39.0,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite,simpson.com,Other,corporate
4,12385,William Maxwell,19.0,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite,abc.org,Other,corporate
5,19314,Rachel Shelton,56.0,female,carpenterian@keller.com,(584)676-7314x00733,Mmbai,Marketing,83979,2022-09-05,10.0,Excellent,10067.0,Mmbai,14.0,NaN,keller.com,Other,corporate
7,13566,Colin Robinson,62.0,female,stanleyamy@clay.com,(028)169-3023,delhi,IT,56741,2022-03-20,7.0,3,10016.0,Mumbai,NaN,Remote,clay.com,Other,corporate
9,17069,Nichole Garcia,20.0,unknown,NaN,268.737.4111x44696,Bangalor,Operations,NaN,2017-11-21,20.0,NaN,10020.0,Bangalore,14.0,Hybrid,unknown@gmail.com,unknown@gmail.com,corporate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6070,15200,Kirk Quinn,57.0,unknown,vmunoz@arellano.org,(067)865-8832x748,mumbai,hr,35392,03/01/2022,12.0,Excellent,10075.0,Delhi,18.0,Hybrid,arellano.org,Other,corporate
6073,11222,Mark Beltran,58.0,female,thomasallen@peters-mitchell.net,468-601-5918x560,delhi,Operations,31650,2022-06-30,13.0,Good,10067.0,Bangalor,27.0,onsite,petersmitchell.net,Other,corporate
6075,13841,Jennifer Myers,45.0,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid,schmidt.com,Other,corporate
6078,18233,Richard Rodriguez,48.0,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote,ortizwong.com,Other,corporate
6079,14157,Lucas Ramsey,18.0,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote,petersreyes.info,Other,corporate

In [746]:
df['Domain'] = df['Domain'].fillna(df['Domain'].mode)

In [747]:
df['Domain'].isna().sum()

np.int64(0)

#  Phone Number

In [748]:
df['Phone_Number'].value_counts().head(20)

Phone_Number
12345                     19
+91 9876543210            18
987 654 3210              17
abcdef                    15
001-019-194-2744x70938     1
528-203-6578               1
+1-015-044-2363x77489      1
+1-111-921-9455x028        1
326.539.9841               1
862.555.7437x566           1
001-080-715-5689x268       1
1139018681                 1
+1-108-550-5011x4112       1
050.572.6766               1
(584)676-7314x00733        1
965.752.9562x446           1
(028)169-3023              1
001-056-326-2176           1
001-411-146-9146x858       1
+1-772-724-5074x348        1
Name: count, dtype: int64

In [749]:
df['Cleaned_Phone'] = df['Phone_Number'].astype(str).replace(r'\D' , '' ,regex = True)

In [750]:
# Extract country code (first 1 - 3 dgit if number >  10 digits)
def get_country_code(number):
    if pd.isnull(number):
        return np.nan
    if len(number) <= 10:
        return np.nan
    return number[:-10] # everything before last 10 digit
df['Country_Code'] = df['Cleaned_Phone'].apply(get_country_code)

In [751]:
df['Country_Code'].isnull().sum()

np.int64(1996)

In [752]:
def get_local_number(number):
    if pd.isnull(number) or len(number) < 10:
        return np.nan
    return number[-10:]
df['Local_Number'] = df['Cleaned_Phone'].apply(get_local_number)

In [753]:
df['Is_Valid_Number'] = df['Local_Number'].notnull()

# Salary

In [754]:
df['Salary'].isnull().sum()

np.int64(54)

In [755]:
salary_series = df['Salary']

In [756]:
salary_str = salary_series.astype(str).str.strip()

In [757]:
unique_salaries = salary_str.unique()

In [758]:
unique_salaries

array(['104695.6', '146215', '124286', ..., '148166', '39682',
       '127574.42'], shape=(5881,), dtype=object)

In [760]:
def salary_forest_type(s):
    s=str(s).strip()
    if s=='nan':
        return 'Missing'
    elif any(c.isalpha() for c in s):
        return 'Contains letters (k, M , etc.)'
    elif any(c in '$5' for c in s):
        return 'Currency / coma'
    elif s.replace('.','',1).isdigit():
        return 'Numeric'
    else:
        return 'Other / invalid'
Salary_Forest = salary_series.apply(salary_forest_type)

#check counts per forest type
Salary_Forest.value_counts()

Salary
Numeric            3521
Currency / coma    2466
Missing              54
Other / invalid      33
Name: count, dtype: int64

In [761]:
currency_comma_mask = salary_str.str.contains(r'[₹$€,]', regex = True)

In [762]:
currency_comma_mask

0       False
1       False
2       False
3       False
4       False
        ...
6075    False
6076    False
6077    False
6078    False
6079    False
Name: Salary, Length: 6074, dtype: bool

In [763]:
unique_currency_comma = salary_str[currency_comma_mask].unique()

In [764]:
unique_currency_comma

array(['₹102348', '₹125315', '₹175543', '₹137382', '₹187279', '₹139612',
       '₹113686', '₹156506', '₹49253', '₹166869', '₹176030', '₹198546',
       '₹37878', '₹33159', '₹60766', '₹43517', '₹39918', '₹59994',
       '₹78153', '₹49741', '₹45280', '₹34340', '₹182322', '₹133002',
       '₹153803', '₹131721', '₹57893', '₹117997', '₹70227', '₹80991',
       '₹41307', '₹117318', '₹58272', '₹82455', '₹193203', '₹173992',
       '₹84693', '₹181899', '₹44298', '₹31609', '₹198427', '₹124475',
       '₹63535', '₹79553', '₹125560', '₹60472', '₹138030', '₹89483',
       '₹185699', '₹118298', '₹30686', '₹62460', '₹45846'], dtype=object)

In [765]:
print("Total unique currency/comma formats:", len(unique_currency_comma))
print("Sample unique currency/comma formats:")
print(unique_currency_comma[:53])

Total unique currency/comma formats: 53
Sample unique currency/comma formats:
['₹102348' '₹125315' '₹175543' '₹137382' '₹187279' '₹139612' '₹113686'
 '₹156506' '₹49253' '₹166869' '₹176030' '₹198546' '₹37878' '₹33159'
 '₹60766' '₹43517' '₹39918' '₹59994' '₹78153' '₹49741' '₹45280' '₹34340'
 '₹182322' '₹133002' '₹153803' '₹131721' '₹57893' '₹117997' '₹70227'
 '₹80991' '₹41307' '₹117318' '₹58272' '₹82455' '₹193203' '₹173992'
 '₹84693' '₹181899' '₹44298' '₹31609' '₹198427' '₹124475' '₹63535'
 '₹79553' '₹125560' '₹60472' '₹138030' '₹89483' '₹185699' '₹118298'
 '₹30686' '₹62460' '₹45846']

In [766]:
df['Salary'] = df['Salary'].astype(str).str.replace('₹' , '' , regex = False)

In [767]:
df['Salary'] = pd.to_numeric(df['Salary'] , errors = 'coerce')